### ISSUE TITLE
GSOC Admin Tasks

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/edit-fonts-activity#1]
- [x] thank accepted proposal and mentors
- [x] create github repo github.com/sugarlab/sugar-font-activity
- [x] create github repo gh-pages blog, starting with proposal solicitation text 
- [x] DC apply to join sugar labs membership
- [x] EH apply to join sugar labs membership
- [x] YA apply to join sugar labs membership
- [x] add yash's proposal to blog
- [x] add DC's js/python email to blog
- [x] add blog to table in https://wiki.sugarlabs.org/go/Summer_of_Code/2016
- [ ] thank all applicants and ask them to  review the project :) 
- [x] add to site biographical information on contributors
- [x] add to cal the milestone dates, share with 3 team

**Comment by davelab6** [comment]
@YashAgarwal please add your proposal to the blog in the gh-pages branch of this repo, and let us know here if you have any trouble. Probably add the PDF to https://github.com/sugarlabs/font-editor-activity/tree/gh-pages/files and then make a short text linking to it?

**Comment by YashAgarwal** [comment]
have uploaded a pdf to 
https://github.com/sugarlabs/font-editor-activity/tree/gh-pages/files/SugarGSoC2016YashAgarwalProposal.pdf

**Comment by davelab6** [comment]
The file is good! Next step is to make a blog post the links to it and explains it. Also, please add the source file for the PDF :) 

This issue has a set of tasks (with the "github flavor markdown" markup) so let's keep it open until all the tasks are checked off :)

**Comment by davelab6** [comment]
@YashAgarwal Hope you can upload an updated source file (or even markdown copy :)  soon

**Comment by YashAgarwal** [comment]
@davelab6  here is the docs link for my proposal, I'll upload markdown in an hour
https://docs.google.com/document/d/1aemTOw8WbOjfLg_2LjZRPe51nWuv4Xo0ms9MTWMf0wI/edit?usp=sharing

**Comment by YashAgarwal** [comment]
@davelab6  I have added the markdown for the proposal, the markdown may be a little messy-- using it for the first time

**Comment by davelab6** [comment]
@YashAgarwal it was fine, the only issue was that the numbered lists were not working quite right, but I fixed them up :) 

@eliheuer and @YashAgarwal are you both members now?

**Comment by YashAgarwal** [comment]
I did send a mail in the format you specified, but haven't received a
reply/notification yet, do they send those?

**Comment by davelab6** [comment]
@YashAgarwal did you get a confirmation?

**Comment by YashAgarwal** [comment]
No, I haven't. Should I send it again?

**Comment by davelab6** [comment]
No its ok, maybe we need to pass your evaluation stage in the warm up
period of GSOC before you can be confirmed as a Member :)

**Comment by davelab6** [comment]
>  add to site biographical information on contributors

I added a profile for me - https://sugarlabs.github.io/edit-fonts-activity/profiles/dave-crossland - please do add your own when you have a moment :)

**Comment by YashAgarwal** [comment]
I got my membership confirmation mail today, should I close this?

**Comment by davelab6** [comment]
Great to know! Please leave it open as I need to thank all applicants and ask them to review the project :)
