### ISSUE TITLE
Create a new font, and saving it

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/edit-fonts-activity#32]
- [ ] The Number 1 feature for a font editor in the 'font manager' page is creating a new font
- [x] The Number 1 part 2 feature is saving a new font, in a source format.

**Comment by YashAgarwal** [comment]
Getting a error with saving to sugar file system,
I can save the font outside sugar but inside sugar I am getting this  error:
`ufoLib.UFOLibError : metainfo.plist is missing in /save/file/path` while saving the file using the following commands

``` python
file_name = os.path.join(self.get_activity_root(), 'data',
                                 '%s.ufo' % self.metadata['title'])
file_obj = open(file_name, 'w')
self.main_font.save(file_name)
```

**Comment by davelab6** [comment]
Can activities save their files inside themselves? I thought they would be
saved into the journal.

**Comment by YashAgarwal** [comment]
I think the journal entry stores a link to the file which is stored in the activity data folder

**Comment by davelab6** [comment]
https://developer.sugarlabs.org/sugar3/sugar3.datastore.datastore.html
perhaps

**Comment by YashAgarwal** [comment]
oh, I can save the file just fine at the specified path
the error is caused by 

``` python
datastore.write(jobject, transfer_ownership=True)
```

Error is:
`ValueError: No file found at dbus.String(u 'path/to/ufo/file' )`

**Comment by davelab6** [comment]
I believe the 'new font' feature now just need to be confirmed in the next .xo build, but seems clear from the screencast in https://sugarlabs.github.io/edit-fonts-activity/week-6-work that its working. 

@YashAgarwal for save, is this working with ufo zip format?

**Comment by davelab6** [comment]
I believe the 'new font' feature now just need to be confirmed in the next .xo build, but seems clear from the screencast in https://sugarlabs.github.io/edit-fonts-activity/week-6-work that its working.

@YashAgarwal for save, is this working with ufo zip format?

**Comment by davelab6** [comment]
Currently on the XO-4, the 'new font' button on the welcome screen doesn't work, but saving using the top toolbar button works :)
