### ISSUE TITLE
Loading a font

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/edit-fonts-activity#33]
- [x] The Number 2 feature is loading a previously saved font (in source format)

**Comment by YashAgarwal** [comment]
loading the ufo is done using defcon

``` python
self.main_path = "ufo/sample.ufo"
self.main_font = Font(self.main_path)       
```

for some ufo files this fails and gives the error

```
Error: defcon.errors.DefconError: the kerning data is not valid
```

saving a ufo file is also done through defcon

``` python
self.main_font.save(file_name)
```

but I'm getting the same error as above for all the ufo files I tried

**Comment by YashAgarwal** [comment]
Using Object Chooser I am not able to see the files corresponding to the following mime types

```
application/x-font-opentype
application/font-sfnt
application/x-plist
application/xml
application/octet-stream
```

I have added all of them in my activity.info [file](https://github.com/sugarlabs/edit-fonts-activity/blob/master/activity/activity.info)

and here's how I'm calling the Object Chooser dialog

``` python
try:
    chooser = ObjectChooser(
        parent=self,
        what_filter=self.get_bundle_id(),
        filter_type=FILTER_TYPE_MIME_BY_ACTIVITY)
except:
    chooser = ObjectChooser(parent=self,
                            what_filter=mime.GENERIC_TYPE_TEXT)
```

I only see the above-mentioned file types if I select the Anything filter in the Object Chooser dialog

**Comment by YashAgarwal** [comment]
I ran `Gio.content_type_guess("file.plist", None)[0]` which gives the output `application/octet-stream`

**Comment by davelab6** [comment]
Can you set the dialog to open with 'Anything' preselected?

If not, I guess the OS has a mime registry that lacks definitions for these mime types. Perhaps @quozl knows how OLPC OS mime types are defined, and can suggest how you might be able to get these added to the next release... 

Or, you could use `application/zip` which should allow you to pick `.ufoz` files - this is cutting edge technology, specified in draft form at http://unifiedfontobject.org/roadmap , but I think it would be good for Sugar as its more compact on-disk. 

Then with the file object returned by the `ObjectChooser()`, you can unzip it with Python, and then deal with its files directly, I guess?

**Comment by YashAgarwal** [comment]
> Can you set the dialog to open with 'Anything' preselected?

I don't know the syntax for this, but I'll look for it

> Or, you could use application/zip which should allow you to pick .ufoz files - this is cutting edge technology, specified in draft form at http://unifiedfontobject.org/roadmap , but I think it would be good for Sugar as its more compact on-disk.
> 
> Then with the file object returned by the ObjectChooser(), you can unzip it with Python, and then deal with its files directly, I guess?

This sounds doable, I'll start with this then

**Comment by quozl** [comment]
OLPC OS on Fedora 18 and _also_ Ubuntu 16.04 lack any definition of;
- MIME types `application/x-font-opentype`, `application/font-sfnt` or `application/x-plist`,
- file types `.plist`, or `.ufo`.

Don't restrict your activity to a presumed future operating system release.

Use a local MIME registry.  This is to reside in `~/.local/share/mime` and may contain `magic`, `globs` or other files.  `strace -e open` has been used to prove.

You might select relevant lines from a later version of `/usr/share/file/magic` that describe your file formats, and add them to `~/.local/share/mime/magic` under control of the activity.

**Comment by davelab6** [comment]
@YashAgarwal is the ufo zip format working for load and save?

**Comment by davelab6** [comment]
It work!
