### ISSUE TITLE
Git submodules

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/edit-fonts-activity#40]
Instead of copying the entire source tree of other git repos into the project directly, use git submodules to include them

**Comment by YashAgarwal** [comment]
adding defcon as a sub module doesn't work, 
I need to add `defcon/Lib/` as `defcon/` to make the activity recognise defcon as a module 
this goes for every other library I need in my activity

**Comment by samdroid-apps** [comment]
There was previously a bug in the bundlebuilder that meant submodules were not built into sugar bundles.  A fix for that bug was merged in Sugar 0.109.0.1 (the most recent release).  Maybe try updating to the very latest sugar-toolkit-gtk3 version?

**Comment by davelab6** [comment]
I see that @YashAgarwal added fontmake as a submodule, but didn't add the `.gitmodule` file; I've addressed this in https://github.com/sugarlabs/edit-fonts-activity/pull/60

**Comment by davelab6** [comment]
Rather than use git submodules to show the code is from 3rd parties, let's use a directory named that way (so its self-describing) to give us more control about code layout:

```
# all our code lives in /editfonts, like this:
/editfonts/our-code.py
# and we place 3rd party libraries in a folder named that way to clearly separate them:
/third_party/
# we copy 3rd party libraries here, do not use git submodules, to avoid too many subdirectories, like this
/third_party/defcon/__init__.py
# and NOT like this
/third_party/defcon/Lib/defcon/__init__.py
```
