### ISSUE TITLE
Unknown contour type found in NotoSerif.ttf

### ISSUE THREAD

**Issue by YashAgarwal** [sugarlabs/edit-fonts-activity#44]
``` xml
      <point x="39" y="86" type="line" smooth="yes"/>
      <point x="69" y="86"/>
      <point x="111" y="99"/>
      <point x="145" y="135"/>
      <point x="176" y="197"/>
      <point x="195" y="246" type="qcurve" smooth="yes"/>
```

there are 4 points before a qcurve type font inside this glyph file. Trufont also crashes while rendering this segment so I'll mark it as someday for now

I guess this maybe related to spiro spline fitting

**Comment by davelab6** [comment]
Please  also file an issue on trufont

**Comment by davelab6** [comment]
Spiro is totally different.

This is a regular truetype quadratic outline and you need to convert it to
a cubic with github.com/googlei18n/cu2qu

**Comment by adrientetar** [comment]
It crashes because you're using an old version.

**Comment by davelab6** [comment]
@YashAgarwal did you update everything?
