### ISSUE TITLE
Make a mock UI for the welcome page

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/edit-fonts-activity#78]
Welcome page need a mock; I suggest 4 panels that quarter the page: 
- [x] top left: Sample Font
- [x] top right: New blank font
- [x] bottom left: Load file
- [x] bottom right: Import OTF/TTF

Also on the top bar, 
- [x] change the configuration of the activity name so that the long input box is not visible and instead accessed by the activity icon's dropdown menu.
- [x] ~~~remove the telepathy circle icon completly~~~
- [x] add buttons for welcome, manager, summary and editor pages (but note that on the welcome page these wont be active sometimes
- [x] add load, save, import, export buttons to the top bar

**Comment by eliheuer** [comment]
I made a blog post about this here: https://sugarlabs.github.io/edit-fonts-activity//welcome-page-ux-concept.html

**Comment by YashAgarwal** [comment]
This is my Progress so far
![screenshot](https://raw.githubusercontent.com/sugarlabs/edit-fonts-activity/gh-pages/files/img/screenshot-welcome-screen.png)
I should be done with it by tomorrow

**Comment by davelab6** [comment]
I noticed in https://github.com/sugarlabs/edit-fonts-activity/issues/78#issuecomment-237417844 that the colors used in the button SVGs are the same as the mock; but the svg used for the actiivty icon at top left is red/yellow. Would be great to keep this open until the buttons use the user-colors :)

**Comment by YashAgarwal** [comment]
@davelab6  I don't think we need to remove the telepathy circle icon completely as it is incorporated in the ActivityToolbarButton class in the sugar3 toolkit/graphics and to remove it I'll have to make a subclass of the ActivityToolbarButto

**Comment by davelab6** [comment]
Sounds good!
